### ISSUE TITLE
Running it on my laptop

### ISSUE THREAD

**Issue by oren** [IronOxidizer/lemmy-lite#1]
is there a way to run it on my laptop without nginx? i tried `cargo build` but don't know what's the next step

**Comment by IronOxidizer** [comment]
Unfortunately, you need nginx to serve static content (it's much faster than actix's static serving since it leverages the kernel to serve static content asynchronously and it does path handling and gzipping cleaner than actix). To run it, you need to use nightly like so:

- `cargo +nightly build` if you want the binary
- `cargo +nighly run` if you simply want to run it

You need to have nginx with the static files in the right location. You can start nginx using the following command `systemctl start nginx` assuming you use systemd.

For more information, you can follow the guide in the [README](https://github.com/IronOxidizer/lemmy-lite#installation).
